#!/bin/bash
# mp-base-upgrade
: ${MP_PREFIX:="/opt/local"}
: ${MP_SVNCMD:=$(which svn)}
: ${MP_SVNTRUNK:="${MP_PREFIX}/var/macports/sources/svn.macports.org/trunk"}
: ${MP_SVNBASE:="${MP_SVNTRUNK}/base"}
: ${MP_SVNBASEROOT:=$(svn info --show-item wc-root ${MP_SVNBASE})}
if [ "${MP_PREFIX}" = "/opt/local" ];then
  CONFIGURE_ARGS="--prefix=${MP_PREFIX} --enable-readline"
else
  CONFIGURE_ARGS="--prefix=${MP_PREFIX} --enable-readline --with-tclpackage=${MP_PREFIX}/Library/Tcl --with-applications-dir=${MP_PREFIX}/Applications"
fi
echo "CONFIGURE_ARGS=${CONFIGURE_ARGS}"
cd "${MP_SVNBASE}"
${MP_SVNCMD} upgrade ${MP_SVNBASEROOT}
${MP_SVNCMD} up ${MP_SVNBASEROOT}
make distclean
./configure ${CONFIGURE_ARGS}
make
sudo make install
make distclean
port version
