#!/bin/bash
# mp-portindex-dports
# Set vars if not set.
: ${MP_PREFIX:="/opt/local"}
: ${MP_SVNCMD:=$(which svn)}
: ${MP_SVNTRUNK:="${MP_PREFIX}/var/macports/sources/svn.macports.org/trunk"}
: ${MP_SVNDPORTS:="${MP_SVNTRUNK}/dports"}
echo "MP_SVNDPORTS=${MP_SVNDPORTS}"
portindex "${MP_SVNDPORTS}"
