#!/bin/sh
# mp-port-clean-find-work

# Set vars if not set.
: ${MP_PREFIX:="/opt/local"}
: ${MP_SVNTRUNK:="${MP_PREFIX}/var/macports/sources/svn.macports.org/trunk"}
: ${MP_SVNDPORTS:="${MP_SVNTRUNK}/dports"}

DIRS=$(find $MP_SVNDPORTS -depth 3 -type l -name work -exec echo {} \; | awk -F/ '{print $(NF-2)"/"$(NF-1)}')
#echo "MP_PREFIX: ${MP_PREFIX}"
#echo "MP_SVNDPORTS: ${MP_SVNDPORTS}"
#echo "DIRS: ${DIRS}"
for DIR in ${DIRS};do
    sudo port clean $MP_SVNDPORTS/$DIR
done
