#!/bin/bash
# mp-grid-port-rdeps
if [[ $# -eq 0 || $1 == "help" ]]
then
    me=`basename $0`
    echo "${me} <stdin> # port -q rdeps $@"
    echo "Usage example:"
    echo "${me} zlib"
    echo "${me} dependentof:zlib"
    exit 1
fi

port -q rdeps $@ | sed -e 's/  /\.\./g' -e 's/^\.\./  /g' -e 's/\.\./\. /g' -e 's/\. \([^\.]\)/\| \1/g' &&
exit 0
