#!/bin/sh
# mp-svn-diff-port
# Get svn diff for "port dir <stdin>"
: ${MP_SVNCMD:="/opt/local/bin/svn"}
CMD="port dir $@ | sort -u"
#echo "${CMD}"
#exit
DIRS=$(eval $CMD)
#echo "${DIRS}"
#exit
${MP_SVNCMD} diff ${DIRS}
