#!/bin/sh
# mp-svn-revert-port
# Recrusive svn revert for "port dir <stdin>"
: ${MP_SVNCMD:=$(which svn)}
CMD="port dir $@ | sort -u"
#echo "${CMD}"
#exit
DIRS=$(eval $CMD)
#echo "${DIRS}"
#exit
${MP_SVNCMD} -R revert ${DIRS}
