#!/bin/sh
# mp-svn-log-port
# Get svn log for "port dir <stdin>"
: ${MP_SVNCMD:=$(which svn)}
CMD="port dir $@ | sort -u"
#echo "${CMD}"
#exit
DIRS=$(eval $CMD)
#echo "${DIRS}"
#exit
${MP_SVNCMD} log ${DIRS}
