#!/bin/sh
# mp-svn-st-port
# Get svn st for "port dir <stdin>"
: ${MP_SVNCMD:=$(which svn)}
CMD="port dir $@ | sort -u"
#echo "${CMD}"
#exit
DIRS=$(eval $CMD)
#echo "${DIRS}"
#exit
${MP_SVNCMD} st ${DIRS}
