#!/bin/bash
# mp-upgrade-trunk-all
. ~/.bash_profile
# Store our active MP* function name.
MP_PREOLD=$(MP-GET)
echo $MP_PREOLD
# Call each MP* function followed by pm-upgrad-trunk
for MPPRE in $(MP-LIST);do
  $MPPRE
  mp-upgrade-trunk
done
# Call our original MP* function to end up where we started
$MP_PREOLD
